name = "DataCollocations"
uuid = "9454e98c-75cb-4dbc-9573-481819719962"
authors = ["SciML Contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[weakdeps]
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"

[extensions]
DataCollocationsDataInterpolationsExt = "DataInterpolations"

[compat]
julia = "1.10"
DataInterpolations = "6.4, 7, 8"

[extras]
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DataInterpolations", "OrdinaryDiffEq", "Test"]
docs = ["Documenter", "DataInterpolations", "OrdinaryDiffEq", "Plots"]